Save and Load system implemented but there is an error.
System.IO.IOException: 'The process cannot access the file 'C:\Users\----\GitKraken\Final-Project\Final Project\bin\Debug\Save.txt' because it is being used by another process.'
I'm in the process of fixing it up.